// ***********************************************************************
// Assembly         : DataStorage
// Author           : G.H.M.H. Schmeits
// Created          : 10-23-2018
//
// Last Modified By : G.H.M.H. Schmeits
// Last Modified On : 05-24-2019
// ***********************************************************************
// <copyright file="InlogData.cs" company="SCHMEITS SOFTWARE">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows;

/// <summary>
/// The DataStorage namespace.
/// </summary>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for DataStorage
namespace DataStorage
{
    using System.Xml.Linq;

    /// <summary>
    /// Class InlogData.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for InlogData
    public class InlogData
    {
        /// <summary>
        /// Logins the data get.
        /// </summary>
        /// <returns>List&lt;InlogDataRecords&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LoginDataGet
        public static List<InlogDataRecords> LoginDataGet()
        {
            var inlogData = new List<InlogDataRecords>();
            try
            {
                var query = "SELECT * FROM login_code";
                var dt = General.ExecuteQueryCommandReturnTable(query);
                inlogData = (from DataRow row in dt.Rows
                    select new InlogDataRecords
                    {
                        IdLoginCode = Convert.ToInt64(row["idlogin_code"].ToString()),
                        LoginURL = row["login_url"].ToString(),
                        LoginAttributeUsername = row["login_attribute_username"].ToString(),
                        LoginAttributePassword = row["login_attribute_password"].ToString(),
                        LoginAttributeButton = row["login_attribute_button"].ToString(),
                        LoginTagUsername = row["login_tagname_user"].ToString(),
                        LoginTagPassword = row["login_tagname_password"].ToString(),
                        LoginTagButton = row["login_tagname_button"].ToString(),
                        LoginValueUsername = row["login_user_value"].ToString(),
                        LoginValuePassword = row["login_password_value"].ToString(),
                        LoginMachinecode = row["login_machine_code"].ToString(),
                        LoginAttributeExtra1 = row["login_attribute_extra1"].ToString(),
                        LoginAttributeExtra2 = row["login_attribute_extra2"].ToString(),
                        LoginAttributeExtra3 = row["login_attribute_extra3"].ToString(),
                        LoginTagnameExtra1 = row["login_tagname_extra1"].ToString(),
                        LoginTagnameExtra2 = row["login_tagname_extra2"].ToString(),
                        LoginTagnameExtra3 = row["login_tagname_extra3"].ToString(),
                        LoginDescriptionExtra1 = row["login_description_extra1"].ToString(),
                        LoginDescriptionExtra2 = row["login_description_extra2"].ToString(),
                        LoginDescriptionExtra3 = row["login_description_extra3"].ToString(),
                        LoginOrder1 = row["login_order1"].ToString(),
                        LoginOrder2 = row["login_order2"].ToString(),
                        LoginOrder3 = row["login_order3"].ToString(),
                        LoginOrder4 = row["login_order4"].ToString(),
                        LoginOrder5 = row["login_order5"].ToString(),
                        LoginOrder6 = row["login_order6"].ToString(),
                        LoginAction1 = row["login_action1"].ToString(),
                        LoginAction2 = row["login_action2"].ToString(),
                        LoginAction3 = row["login_action3"].ToString(),
                        LoginAction4 = row["login_action4"].ToString(),
                        LoginAction5 = row["login_action5"].ToString(),
                        LoginAction6 = row["login_action6"].ToString(),
                        LoginName = row["login_name"].ToString()
                    }).ToList();
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
                General.LogMessageDatabase(e.Message + "\r\n\r\n" + e.StackTrace + "\r\n\r\n" + e.Source, 4);
            }

            return inlogData;
        }

        /// <summary>
        /// Class InlogDataRecords.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for InlogDataRecords
        public class InlogDataRecords
        {
            /// <summary>
            /// Gets or sets the identifier login code.
            /// </summary>
            /// <value>The identifier login code.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for IdLoginCode
            public long IdLoginCode { get; set; }
            /// <summary>
            /// Gets or sets the login attribute button.
            /// </summary>
            /// <value>The login attribute button.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginAttributeButton
            public string LoginAttributeButton { get; set; }
            /// <summary>
            /// Gets or sets the login attribute password.
            /// </summary>
            /// <value>The login attribute password.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginAttributePassword
            public string LoginAttributePassword { get; set; }
            /// <summary>
            /// Gets or sets the login attribute username.
            /// </summary>
            /// <value>The login attribute username.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginAttributeUsername
            public string LoginAttributeUsername { get; set; }
            /// <summary>
            /// Gets or sets the login machinecode.
            /// </summary>
            /// <value>The login machinecode.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginMachinecode
            public string LoginMachinecode { get; set; }
            /// <summary>
            /// Gets or sets the login tag button.
            /// </summary>
            /// <value>The login tag button.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginTagButton
            public string LoginTagButton { get; set; }
            /// <summary>
            /// Gets or sets the login tag password.
            /// </summary>
            /// <value>The login tag password.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginTagPassword
            public string LoginTagPassword { get; set; }
            /// <summary>
            /// Gets or sets the login tag username.
            /// </summary>
            /// <value>The login tag username.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginTagUsername
            public string LoginTagUsername { get; set; }
            /// <summary>
            /// Gets or sets the login URL.
            /// </summary>
            /// <value>The login URL.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginURL
            public string LoginURL { get; set; }
            /// <summary>
            /// Gets or sets the login value password.
            /// </summary>
            /// <value>The login value password.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginValuePassword
            public string LoginValuePassword { get; set; }
            /// <summary>
            /// Gets or sets the login value username.
            /// </summary>
            /// <value>The login value username.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for LoginValueUsername
            public string LoginValueUsername { get; set; }


            public string LoginAttributeExtra1 { get; set; }
            public string LoginAttributeExtra2 { get; set; }
            public string LoginAttributeExtra3 { get; set; }
            public string LoginTagnameExtra1 { get; set; }
            public string LoginTagnameExtra2 { get; set; }
            public string LoginTagnameExtra3 { get; set; }
            public string LoginDescriptionExtra1 { get; set; }
            public string LoginDescriptionExtra2 { get; set; }

            public string LoginDescriptionExtra3 { get; set; }
            public string LoginOrder1 { get; set; }
            public string LoginOrder2 { get; set; }
            public string LoginOrder3 { get; set; }
            public string LoginOrder4 { get; set; }
            public string LoginOrder5 { get; set; }
            public string LoginOrder6 { get; set; }
            public string LoginAction1 { get; set; }
            public string LoginAction2 { get; set; }
            public string LoginAction3 { get; set; }
            public string LoginAction4 { get; set; }
            public string LoginAction5 { get; set; }
            public string LoginAction6 { get; set; }

            public string LoginName { get; set; }
        }
    }
}