// ***********************************************************************
// Assembly         : DataStorage
// Author           : G.H.M.H. Schmeits
// Created          : 04-23-2018
//
// Last Modified By : G.H.M.H. Schmeits
// Last Modified On : 05-24-2019
// ***********************************************************************
// <copyright file="NewElements.cs" company="SCHMEITS SOFTWARE">
//     Copyright ©  2018
// </copyright>
// <summary></summary>
// ***********************************************************************
/// <summary>
/// The DataStorage namespace.
/// </summary>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for DataStorage
namespace DataStorage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    using DataStorage.Annotations;

    /// <summary>
    /// Class NewElements.
    /// </summary>
    /// <seealso cref="System.ComponentModel.INotifyPropertyChanged" />
    public class NewElements : INotifyPropertyChanged
    {
        /// <summary>
        /// The elements results
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _elementsResults
        private static List<AllElements> _elementsResults;

        /// <summary>
        /// Gets or sets the urlname.
        /// </summary>
        /// <value>The urlname.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _urlname
        private static string _urlname { get; set; }

        /// <summary>
        /// Gets or sets the element results.
        /// </summary>
        /// <value>The element results.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ElementResults
        public static List<AllElements> ElementResults { get; set; }

        /// <summary>
        /// Gets all elements.
        /// </summary>
        /// <param name="urlname">The urlname.</param>
        /// <returns>List&lt;AllElements&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetAllElements
        public static List<AllElements> GetAllElements(string urlname)
        {
            return _elementsResults;
        }

        /// <summary>
        /// Inis the elements.
        /// </summary>
        /// <param name="urlname">The urlname.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for IniElements
        public static void IniElements(string urlname)
        {
            _urlname = urlname;
            _elementsResults = new List<AllElements>();
        }

        /// <summary>
        /// Sets the elements.
        /// </summary>
        /// <param name="tagname">The tagname.</param>
        /// <param name="tekst">The tekst.</param>
        /// <param name="accept">The accept.</param>
        /// <param name="accesskey">The accesskey.</param>
        /// <param name="align">The align.</param>
        /// <param name="alt">The alt.</param>
        /// <param name="autocomplete">The autocomplete.</param>
        /// <param name="autofocus">The autofocus.</param>
        /// <param name="border">The border.</param>
        /// <param name="charset">The charset.</param>
        /// <param name="checked1">The checked1.</param>
        /// <param name="class1">The class1.</param>
        /// <param name="contenteditable">The contenteditable.</param>
        /// <param name="contextmenu">The contextmenu.</param>
        /// <param name="coords">The coords.</param>
        /// <param name="crossorigin">The crossorigin.</param>
        /// <param name="dir">The dir.</param>
        /// <param name="dirname">The dirname.</param>
        /// <param name="disabled">The disabled.</param>
        /// <param name="download">The download.</param>
        /// <param name="draggable">The draggable.</param>
        /// <param name="dropzone">The dropzone.</param>
        /// <param name="form">The form.</param>
        /// <param name="formaction">The formaction.</param>
        /// <param name="formenctype">The formenctype.</param>
        /// <param name="formmethod">The formmethod.</param>
        /// <param name="formnovalidate">The formnovalidate.</param>
        /// <param name="formtarget">The formtarget.</param>
        /// <param name="frameborder">The frameborder.</param>
        /// <param name="height">The height.</param>
        /// <param name="hidden">The hidden.</param>
        /// <param name="href">The href.</param>
        /// <param name="hreflang">The hreflang.</param>
        /// <param name="hspace">The hspace.</param>
        /// <param name="id">The identifier.</param>
        /// <param name="ismap">The ismap.</param>
        /// <param name="lang">The language.</param>
        /// <param name="list">The list.</param>
        /// <param name="longdesc">The longdesc.</param>
        /// <param name="marginheight">The marginheight.</param>
        /// <param name="marginwidth">The marginwidth.</param>
        /// <param name="max">The maximum.</param>
        /// <param name="maxlength">The maxlength.</param>
        /// <param name="media">The media.</param>
        /// <param name="min">The minimum.</param>
        /// <param name="multiple">The multiple.</param>
        /// <param name="name">The name.</param>
        /// <param name="pattpern">The pattpern.</param>
        /// <param name="placeholder">The placeholder.</param>
        /// <param name="readonly1">The readonly1.</param>
        /// <param name="rel">The relative.</param>
        /// <param name="required">The required.</param>
        /// <param name="rev">The rev.</param>
        /// <param name="sandbox">The sandbox.</param>
        /// <param name="scrolling">The scrolling.</param>
        /// <param name="shape">The shape.</param>
        /// <param name="size">The size.</param>
        /// <param name="sizes">The sizes.</param>
        /// <param name="spellcheck">The spellcheck.</param>
        /// <param name="src">The source.</param>
        /// <param name="srcdoc">The srcdoc.</param>
        /// <param name="step">The step.</param>
        /// <param name="style">The style.</param>
        /// <param name="tabindex">The tabindex.</param>
        /// <param name="target">The target.</param>
        /// <param name="title">The title.</param>
        /// <param name="translage">The translage.</param>
        /// <param name="type">The type.</param>
        /// <param name="usemap">The usemap.</param>
        /// <param name="value">The value.</param>
        /// <param name="vspace">The vspace.</param>
        /// <param name="width">The width.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for SetElements
        public static void SetElements(
            string tagname,
            string tekst,
            string accept,
            string accesskey,
            string align,
            string alt,
            string autocomplete,
            string autofocus,
            string border,
            string charset,
            string checked1,
            string class1,
            string contenteditable,
            string contextmenu,
            string coords,
            string crossorigin,
            string dir,
            string dirname,
            string disabled,
            string download,
            string draggable,
            string dropzone,
            string form,
            string formaction,
            string formenctype,
            string formmethod,
            string formnovalidate,
            string formtarget,
            string frameborder,
            string height,
            string hidden,
            string href,
            string hreflang,
            string hspace,
            string id,
            string ismap,
            string lang,
            string list,
            string longdesc,
            string marginheight,
            string marginwidth,
            string max,
            string maxlength,
            string media,
            string min,
            string multiple,
            string name,
            string pattpern,
            string placeholder,
            string readonly1,
            string rel,
            string required,
            string rev,
            string sandbox,
            string scrolling,
            string shape,
            string size,
            string sizes,
            string spellcheck,
            string src,
            string srcdoc,
            string step,
            string style,
            string tabindex,
            string target,
            string title,
            string translage,
            string type,
            string usemap,
            string value,
            string vspace,
            string width,
            Boolean checktext)
        {

            var checkvalue = 1;
            if (checktext == false)
            {
                checkvalue = 0;
            }

            _elementsResults.Add(
                new AllElements
                    {
                        elementTagname = tagname,
                        elementText = tekst,
                        elementAccept = accept,
                        elementCheck = true, 
                        elementAccesskey = accesskey,
                        elementAlign = align,
                        elementAlt = alt,
                        elementAutocomplete = autocomplete,
                        elementAutofocus = autofocus,
                        elementBorder = border,
                        elementCharset = charset,
                        elementChecked = checked1,
                        elementClass = class1,
                        elementContenteditable = contenteditable,
                        elementContextmenu = contextmenu,
                        elementCoords = coords,
                        elementCrossorigin = crossorigin,
                        elementDir = dir,
                        elementDirname = dirname,
                        elementDisabled = disabled,
                        elementDownload = download,
                        elementDraggable = draggable,
                        elementDropzone = dropzone,
                        elementForm = form,
                        elementFormaction = formaction,
                        elementFormenctype = formenctype,
                        elementFormmethod = formmethod,
                        elementFormnovalidate = formnovalidate,
                        elementFormtarget = formtarget,
                        elementFrameborder = frameborder,
                        elementHeight = height,
                        elementHidden = hidden,
                        elementHref = href,
                        elementHreflang = hreflang,
                        elementHspace = hspace,
                        elementId = id,
                        elementIsmap = ismap,
                        elementLang = lang,
                        elementList = list,
                        elementLongdesc = longdesc,
                        elementMarginheight = marginheight,
                        elementMarginwidth = marginwidth,
                        elementMax = max,
                        elementMaxlength = maxlength,
                        elementMedia = media,
                        elementMin = min,
                        elementMultiple = multiple,
                        elementName = name,
                        elementPattern = pattpern,
                        elementPlaceholder = placeholder,
                        elementReadonly = readonly1,
                        elementRel = rel,
                        elementRequired = required,
                        elementRev = rev,
                        elementSandbox = sandbox,
                        elementScrolling = scrolling,
                        elementShape = shape,
                        elementSize = size,
                        elementSizes = sizes,
                        elementSpellcheck = spellcheck,
                        elementSrc = src,
                        elementSrcdoc = srcdoc,
                        elementStep = step,
                        elementStyle = style,
                        elementTabindex = tabindex,
                        elementTarget = target,
                        elementTitle = title,
                        elementTranslage = translage,
                        elementType = type,
                        elementUsemap = usemap,
                        elementValue = value,
                        elementVspace = vspace,
                        elementWidth = width,
                        elementCheckText = checktext
                    });

            var sql = "INSERT INTO `autotest`.`selenium_elements` ";
            sql += "(`url`, ";
            sql += "`tagname`, ";
            sql += "`text`, ";
            sql += "`accept`, ";
            sql += "`accesskey`, ";
            sql += "`align`, ";
            sql += "`alt`, ";
            sql += "`autocomplete`, ";
            sql += "`autofocus`, ";
            sql += "`border`, ";
            sql += "`charset`, ";
            sql += "`checked`, ";
            sql += "`class`, ";
            sql += "`contenteditable`, ";
            sql += "`contextmenu`, ";
            sql += "`coords`, ";
            sql += "`crossorigin`, ";
            sql += "`dir`, ";
            sql += "`dirname`, ";
            sql += "`disabled`, ";
            sql += "`download`, ";
            sql += "`draggable`, ";
            sql += "`dropzone`, ";
            sql += "`form`, ";
            sql += "`formaction`, ";
            sql += "`formenctype`, ";
            sql += "`formmethod`, ";
            sql += "`formnovalidate`, ";
            sql += "`formtarget`, ";
            sql += "`frameborder`, ";
            sql += "`height`, ";
            sql += "`hidden`, ";
            sql += "`href`, ";
            sql += "`hreflang`, ";
            sql += "`hspace`, ";
            sql += "`id`, ";
            sql += "`ismap`, ";
            sql += "`lang`, ";
            sql += "`list`, ";
            sql += "`longdesc`, ";
            sql += "`marginheight`, ";
            sql += "`marginwidth`, ";
            sql += "`max`, ";
            sql += "`maxlength`, ";
            sql += "`media`, ";
            sql += "`min`, ";
            sql += "`multiple`, ";
            sql += "`name`, ";
            sql += "`pattern`, ";
            sql += "`placeholder`, ";
            sql += "`readonly`, ";
            sql += "`rel`, ";
            sql += "`required`, ";
            sql += "`rev`, ";
            sql += "`sandbox`, ";
            sql += "`scrolling`, ";
            sql += "`shape`, ";
            sql += "`size`, ";
            sql += "`sizes`, ";
            sql += "`spellcheck`, ";
            sql += "`src`, ";
            sql += "`srcdoc`, ";
            sql += "`step`, ";
            sql += "`style`, ";
            sql += "`tabindex`, ";
            sql += "`target`, ";
            sql += "`title`, ";
            sql += "`translage`, ";
            sql += "`type`, ";
            sql += "`usemap`, ";
            sql += "`value`, ";
            sql += "`vspace`, ";
            sql += "`width`,  ";
            sql += "checktext)";
            sql += "VALUES ";
            sql += "('" + _urlname + "', ";
            sql += "'" + tagname + "', ";
            sql += "'" + tekst + "', ";
            sql += "'" + accept + "', ";
            sql += "'" + accesskey + "', ";
            sql += "'" + align + "', ";
            sql += "'" + alt + "', ";
            sql += "'" + autocomplete + "', ";
            sql += "'" + autofocus + "', ";
            sql += "'" + border + "', ";
            sql += "'" + charset + "', ";
            sql += "'" + checked1 + "', ";
            sql += "'" + class1 + "', ";
            sql += "'" + contenteditable + "', ";
            sql += "'" + contextmenu + "', ";
            sql += "'" + coords + "', ";
            sql += "'" + crossorigin + "', ";
            sql += "'" + dir + "', ";
            sql += "'" + dirname + "', ";
            sql += "'" + disabled + "', ";
            sql += "'" + download + "', ";
            sql += "'" + draggable + "', ";
            sql += "'" + dropzone + "', ";
            sql += "'" + form + "', ";
            sql += "'" + formaction + "', ";
            sql += "'" + formenctype + "', ";
            sql += "'" + formmethod + "', ";
            sql += "'" + formnovalidate + "', ";
            sql += "'" + formtarget + "', ";
            sql += "'" + frameborder + "', ";
            sql += "'" + height + "', ";
            sql += "'" + hidden + "', ";
            sql += "'" + href + "', ";
            sql += "'" + hreflang + "', ";
            sql += "'" + hspace + "', ";
            sql += "'" + id + "', ";
            sql += "'" + ismap + "', ";
            sql += "'" + lang + "', ";
            sql += "'" + list + "', ";
            sql += "'" + longdesc + "', ";
            sql += "'" + marginheight + "', ";
            sql += "'" + marginwidth + "', ";
            sql += "'" + max + "', ";
            sql += "'" + maxlength + "', ";
            sql += "'" + media + "', ";
            sql += "'" + min + "', ";
            sql += "'" + multiple + "', ";
            sql += "'" + name + "', ";
            sql += "'" + pattpern + "', ";
            sql += "'" + placeholder + "', ";
            sql += "'" + readonly1 + "', ";
            sql += "'" + rel + "', ";
            sql += "'" + required + "', ";
            sql += "'" + rev + "', ";
            sql += "'" + sandbox + "', ";
            sql += "'" + scrolling + "', ";
            sql += "'" + shape + "', ";
            sql += "'" + size + "', ";
            sql += "'" + sizes + "', ";
            sql += "'" + spellcheck + "', ";
            sql += "'" + src + "', ";
            sql += "'" + srcdoc + "', ";
            sql += "'" + step + "', ";
            sql += "'" + style + "', ";
            sql += "'" + tabindex + "', ";
            sql += "'" + target + "', ";
            sql += "'" + title + "', ";
            sql += "'" + translage + "', ";
            sql += "'" + type + "', ";
            sql += "'" + usemap + "', ";
            sql += "'" + value + "', ";
            sql += "'" + vspace + "', ";
            sql += "'" + width + "', ";
            sql += "'" + checktext + "');";
            General.ExecuteQueryCommand(sql);
        }
        
        /// <summary>
        /// Class ElementsFromDataGrid.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ElementsFromDataGrid
        public class ElementsFromDataGrid
        {
            /// <summary>
            /// Gets or sets the element link.
            /// </summary>
            /// <value>The element link.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementLink
            public string elementLink { get; set; }
            /// <summary>
            /// Gets or sets the identifier selenium element.
            /// </summary>
            /// <value>The identifier selenium element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for idSelenium_element
            public Int64 idSelenium_element { get; set; }

            /// <summary>
            /// Gets or sets the element check.
            /// </summary>
            /// <value>The element check.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementCheck
            public Boolean elementCheck { get; set; }

            public Boolean elementCheckText { get; set; }

            /// <summary>
            /// Gets or sets the element xpath.
            /// </summary>
            /// <value>The element xpath.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementXpath
            public string elementXpath { get; set; }

            /// <summary>
            /// Gets or sets the element tagname.
            /// </summary>
            /// <value>The element tagname.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTagname
            public string elementTagname { get; set; }

            /// <summary>
            /// Gets or sets the element class.
            /// </summary>
            /// <value>The element class.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementClass
            public string elementClass { get; set; }

            /// <summary>
            /// Gets or sets the element href.
            /// </summary>
            /// <value>The element href.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHref
            public string elementHref { get; set; }

            /// <summary>
            /// Gets or sets the element identifier.
            /// </summary>
            /// <value>The element identifier.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementId
            public string elementId { get; set; }

            /// <summary>
            /// Gets or sets the name of the element.
            /// </summary>
            /// <value>The name of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementName
            public string elementName { get; set; }
        }

        /// <summary>
        /// Class AllElements.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AllElements
        public class AllElements
        {
            /// <summary>
            /// Gets or sets the element link.
            /// </summary>
            /// <value>The element link.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementLink
            public string elementLink { get; set; }
            /// <summary>
            /// Gets or sets the element accept.
            /// </summary>
            /// <value>The element accept.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAccept
            public string elementAccept { get; set; } // input

            /// <summary>
            /// Gets or sets the element accesskey.
            /// </summary>
            /// <value>The element accesskey.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAccesskey
            public string elementAccesskey { get; set; } // global

            /// <summary>
            /// Gets or sets the element align.
            /// </summary>
            /// <value>The element align.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAlign
            public string elementAlign { get; set; } // inut {get; set; } img {get; set; } iframe

            /// <summary>
            /// Gets or sets the element alt.
            /// </summary>
            /// <value>The element alt.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAlt
            public string elementAlt { get; set; } // inout {get; set; } img

            /// <summary>
            /// Gets or sets the element autocomplete.
            /// </summary>
            /// <value>The element autocomplete.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAutocomplete
            public string elementAutocomplete { get; set; } // input

            /// <summary>
            /// Gets or sets the element autofocus.
            /// </summary>
            /// <value>The element autofocus.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementAutofocus
            public string elementAutofocus { get; set; } // input

            /// <summary>
            /// Gets or sets the element border.
            /// </summary>
            /// <value>The element border.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementBorder
            public string elementBorder { get; set; } // img

            /// <summary>
            /// Gets or sets the element charset.
            /// </summary>
            /// <value>The element charset.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementCharset
            public string elementCharset { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element checked.
            /// </summary>
            /// <value>The element checked.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementChecked
            public string elementChecked { get; set; } // input

            /// <summary>
            /// Gets or sets the element class.
            /// </summary>
            /// <value>The element class.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementClass
            public string elementClass { get; set; } // global

            /// <summary>
            /// Gets or sets the element contenteditable.
            /// </summary>
            /// <value>The element contenteditable.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementContenteditable
            public string elementContenteditable { get; set; }

            /// <summary>
            /// Gets or sets the element contextmenu.
            /// </summary>
            /// <value>The element contextmenu.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementContextmenu
            public string elementContextmenu { get; set; } // global

            /// <summary>
            /// Gets or sets the element coords.
            /// </summary>
            /// <value>The element coords.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementCoords
            public string elementCoords { get; set; } // a

            /// <summary>
            /// Gets or sets the element crossorigin.
            /// </summary>
            /// <value>The element crossorigin.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementCrossorigin
            public string elementCrossorigin { get; set; } // link {get; set; } img

            /// <summary>
            /// Gets or sets the element dir.
            /// </summary>
            /// <value>The element dir.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDir
            public string elementDir { get; set; } // global

            /// <summary>
            /// Gets or sets the element dirname.
            /// </summary>
            /// <value>The element dirname.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDirname
            public string elementDirname { get; set; } // input

            /// <summary>
            /// Gets or sets the element disabled.
            /// </summary>
            /// <value>The element disabled.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDisabled
            public string elementDisabled { get; set; } // input

            /// <summary>
            /// Gets or sets the element download.
            /// </summary>
            /// <value>The element download.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDownload
            public string elementDownload { get; set; } // a

            /// <summary>
            /// Gets or sets the element draggable.
            /// </summary>
            /// <value>The element draggable.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDraggable
            public string elementDraggable { get; set; } // global

            /// <summary>
            /// Gets or sets the element dropzone.
            /// </summary>
            /// <value>The element dropzone.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementDropzone
            public string elementDropzone { get; set; } // global

            /// <summary>
            /// Gets or sets the element form.
            /// </summary>
            /// <value>The element form.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementForm
            public string elementForm { get; set; } // input

            /// <summary>
            /// Gets or sets the element formaction.
            /// </summary>
            /// <value>The element formaction.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFormaction
            public string elementFormaction { get; set; } // input

            /// <summary>
            /// Gets or sets the element formenctype.
            /// </summary>
            /// <value>The element formenctype.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFormenctype
            public string elementFormenctype { get; set; } // input

            /// <summary>
            /// Gets or sets the element formmethod.
            /// </summary>
            /// <value>The element formmethod.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFormmethod
            public string elementFormmethod { get; set; } // input

            /// <summary>
            /// Gets or sets the element formnovalidate.
            /// </summary>
            /// <value>The element formnovalidate.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFormnovalidate
            public string elementFormnovalidate { get; set; } // input

            /// <summary>
            /// Gets or sets the element formtarget.
            /// </summary>
            /// <value>The element formtarget.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFormtarget
            public string elementFormtarget { get; set; } // input

            /// <summary>
            /// Gets or sets the element frameborder.
            /// </summary>
            /// <value>The element frameborder.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementFrameborder
            public string elementFrameborder { get; set; } // iframe

            /// <summary>
            /// Gets or sets the height of the element.
            /// </summary>
            /// <value>The height of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHeight
            public string elementHeight { get; set; } // input {get; set; } img {get; set; } iframe

            /// <summary>
            /// Gets or sets the element hidden.
            /// </summary>
            /// <value>The element hidden.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHidden
            public string elementHidden { get; set; } // global

            /// <summary>
            /// Gets or sets the element href.
            /// </summary>
            /// <value>The element href.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHref
            public string elementHref { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element hreflang.
            /// </summary>
            /// <value>The element hreflang.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHreflang
            public string elementHreflang { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element hspace.
            /// </summary>
            /// <value>The element hspace.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementHspace
            public string elementHspace { get; set; } // img

            /// <summary>
            /// Gets or sets the element identifier.
            /// </summary>
            /// <value>The element identifier.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementId
            public string elementId { get; set; }

            /// <summary>
            /// Gets or sets the element ismap.
            /// </summary>
            /// <value>The element ismap.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementIsmap
            public string elementIsmap { get; set; } // img

            /// <summary>
            /// Gets or sets the element language.
            /// </summary>
            /// <value>The element language.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementLang
            public string elementLang { get; set; } // global

            /// <summary>
            /// Gets or sets the element list.
            /// </summary>
            /// <value>The element list.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementList
            public string elementList { get; set; } // input

            /// <summary>
            /// Gets or sets the element longdesc.
            /// </summary>
            /// <value>The element longdesc.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementLongdesc
            public string elementLongdesc { get; set; } // img {get; set; } iframe

            /// <summary>
            /// Gets or sets the element marginheight.
            /// </summary>
            /// <value>The element marginheight.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMarginheight
            public string elementMarginheight { get; set; } // iframe

            /// <summary>
            /// Gets or sets the element marginwidth.
            /// </summary>
            /// <value>The element marginwidth.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMarginwidth
            public string elementMarginwidth { get; set; } // iframe

            /// <summary>
            /// Gets or sets the element maximum.
            /// </summary>
            /// <value>The element maximum.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMax
            public string elementMax { get; set; } // input

            /// <summary>
            /// Gets or sets the element maxlength.
            /// </summary>
            /// <value>The element maxlength.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMaxlength
            public string elementMaxlength { get; set; } // input

            /// <summary>
            /// Gets or sets the element media.
            /// </summary>
            /// <value>The element media.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMedia
            public string elementMedia { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element minimum.
            /// </summary>
            /// <value>The element minimum.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMin
            public string elementMin { get; set; } // input

            /// <summary>
            /// Gets or sets the element multiple.
            /// </summary>
            /// <value>The element multiple.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementMultiple
            public string elementMultiple { get; set; } // input

            /// <summary>
            /// Gets or sets the name of the element.
            /// </summary>
            /// <value>The name of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementName
            public string elementName { get; set; } // a, inut, iframe

            /// <summary>
            /// Gets or sets the element pattern.
            /// </summary>
            /// <value>The element pattern.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementPattern
            public string elementPattern { get; set; } // input

            /// <summary>
            /// Gets or sets the element placeholder.
            /// </summary>
            /// <value>The element placeholder.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementPlaceholder
            public string elementPlaceholder { get; set; } // input

            /// <summary>
            /// Gets or sets the element readonly.
            /// </summary>
            /// <value>The element readonly.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementReadonly
            public string elementReadonly { get; set; } // input

            /// <summary>
            /// Gets or sets the element relative.
            /// </summary>
            /// <value>The element relative.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementRel
            public string elementRel { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element required.
            /// </summary>
            /// <value>The element required.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementRequired
            public string elementRequired { get; set; } // input

            /// <summary>
            /// Gets or sets the element rev.
            /// </summary>
            /// <value>The element rev.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementRev
            public string elementRev { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element sandbox.
            /// </summary>
            /// <value>The element sandbox.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSandbox
            public string elementSandbox { get; set; } // iframe

            /// <summary>
            /// Gets or sets the element scrolling.
            /// </summary>
            /// <value>The element scrolling.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementScrolling
            public string elementScrolling { get; set; } // iframe

            /// <summary>
            /// Gets or sets the element shape.
            /// </summary>
            /// <value>The element shape.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementShape
            public string elementShape { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the size of the element.
            /// </summary>
            /// <value>The size of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSize
            public string elementSize { get; set; } // input

            /// <summary>
            /// Gets or sets the element sizes.
            /// </summary>
            /// <value>The element sizes.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSizes
            public string elementSizes { get; set; } // img

            /// <summary>
            /// Gets or sets the element spellcheck.
            /// </summary>
            /// <value>The element spellcheck.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSpellcheck
            public string elementSpellcheck { get; set; }

            /// <summary>
            /// Gets or sets the element source.
            /// </summary>
            /// <value>The element source.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSrc
            public string elementSrc { get; set; } // input {get; set; } img {get; set; } iframe

            /// <summary>
            /// Gets or sets the element srcdoc.
            /// </summary>
            /// <value>The element srcdoc.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementSrcdoc
            public string elementSrcdoc { get; set; } // iframe

            /// <summary>
            /// Gets or sets the element step.
            /// </summary>
            /// <value>The element step.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementStep
            public string elementStep { get; set; } // input

            /// <summary>
            /// Gets or sets the element style.
            /// </summary>
            /// <value>The element style.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementStyle
            public string elementStyle { get; set; } // global

            /// <summary>
            /// Gets or sets the element tabindex.
            /// </summary>
            /// <value>The element tabindex.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTabindex
            public string elementTabindex { get; set; } // global

            /// <summary>
            /// Gets or sets the element tagname.
            /// </summary>
            /// <value>The element tagname.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTagname
            public string elementTagname { get; set; } // global

            /// <summary>
            /// Gets or sets the element target.
            /// </summary>
            /// <value>The element target.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTarget
            public string elementTarget { get; set; } // a {get; set; } link

            /// <summary>
            /// Gets or sets the element text.
            /// </summary>
            /// <value>The element text.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementText
            public string elementText { get; set; } // global

            /// <summary>
            /// Gets or sets the element title.
            /// </summary>
            /// <value>The element title.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTitle
            public string elementTitle { get; set; } // global

            /// <summary>
            /// Gets or sets the element translage.
            /// </summary>
            /// <value>The element translage.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementTranslage
            public string elementTranslage { get; set; } // global

            /// <summary>
            /// Gets or sets the type of the element.
            /// </summary>
            /// <value>The type of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementType
            public string elementType { get; set; } // a {get; set; } link {get; set; } input 

            /// <summary>
            /// Gets or sets the element usemap.
            /// </summary>
            /// <value>The element usemap.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementUsemap
            public string elementUsemap { get; set; } // img

            /// <summary>
            /// Gets or sets the element value.
            /// </summary>
            /// <value>The element value.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementValue
            public string elementValue { get; set; } // input

            /// <summary>
            /// Gets or sets the element vspace.
            /// </summary>
            /// <value>The element vspace.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementVspace
            public string elementVspace { get; set; } // img

            /// <summary>
            /// Gets or sets the width of the element.
            /// </summary>
            /// <value>The width of the element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementWidth
            public string elementWidth { get; set; }

            /// <summary>
            /// Gets or sets the element xpath.
            /// </summary>
            /// <value>The element xpath.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementXpath
            public string elementXpath { get; set; }

            /// <summary>
            /// Gets or sets the element check.
            /// </summary>
            /// <value>The element check.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for elementCheck
            public Boolean elementCheck { get; set; }
            public Boolean elementCheckText { get; set; }

            /// <summary>
            /// Gets or sets the identifier selenium element.
            /// </summary>
            /// <value>The identifier selenium element.</value>
            /// <autogeneratedoc />
            /// TODO Edit XML Comment Template for idSelenium_element
            public Int64 idSelenium_element { get; set; }
        }

        /// <summary>
        /// Occurs when a property value changes.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for PropertyChanged
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Called when [property changed].
        /// </summary>
        /// <param name="propertyName">Name of the property.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for OnPropertyChanged
        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}